$kind: http-request
name: Create Role
method: POST
url: "{{baseUrl}}/api/roles"
order: 1000
headers:
  Content-Type: application/json
  Authorization: "{{authToken}}"
body:
  type: json
  content: |-
    {
      "Code": "tester-delete",
      "Name": "tester more",
      "Description": "tester role more"
    }
