$kind: http-request
name: Update Role
method: PUT
url: "{{baseUrl}}/api/roles/:code"
order: 4000
pathVariables:
  code: admin
headers:
  Content-Type: application/json
  Authorization: "{{authToken}}"
body:
  type: json
  content: |-
    {
      "Name": "Administrator Updated",
      "Description": "Updated admin role"
    }
